/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mo.mo6600;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-30
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class GlItemBVO extends SuperVO
{

	public String hw;
	public String pk_glzb_b;
	public UFBoolean sfltd;
	public String cp;
	public Integer xxaglsl;
	public String lh; 
	public String pk_glzb;
	public Integer clzt;
	public String ph;
	public String glyy;
	public String dh;
	public String cp_id;   
	public String isolationckid; 
	public String note;
	public String pk_freeze;//冻结PK
	public String hwname ;//货位名称
	public String cinventoryid;//存货ID
	public String cspaceid;//货位
	private String pk_corp; //当前公司
	private String dinggai;
	private String tuopan;
	private String dianguanzhi;
	
	
	

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getIsolationckid() {
		return isolationckid;
	}

	public void setIsolationckid(String isolationckid) {
		this.isolationckid = isolationckid;
	}
	public String isolationcpid;
	public String getIsolationcpid() {
		return isolationcpid;
	}

	public void setIsolationcpid(String isolationcpid) {
		this.isolationcpid = isolationcpid;
	}
	public static final String ISOLATIONCPID="isolationcpid";
	public static final String HW = "hw";
	public static final String PK_GLZB_B = "pk_glzb_b";
	public static final String SFLTD = "sfltd";
	public static final String CP = "cp";
	public static final String XXAGLSL = "xxaglsl";
	public static final String LH = "lh";
	public static final String DR = "dr";
	public static final String PK_GLZB = "pk_glzb";
	public static final String CLZT = "clzt";
	public static final String PH = "ph";
	public static final String GLYY = "glyy";
	public static final String DH = "dh";
	public static final String ISOLATIONCKID = "isolationckid";
	public static final String NOTE="note";
	public static final String CINVMAN="cinventoryid";
	public static final String CSPACEID="cspaceid";
	public static final String DINGGAI="dinggai";
	public static final String TUOPAN="tuopan";
	public static final String DIANGUANZHI="dianguanzhi";
	/**
	 * 属性hw的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getHw()
	{
		return hw;
	}

	/**
	 * 属性hw的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newHw
	 *            String
	 */
	public void setHw(String newHw)
	{

		hw = newHw;
	}

	/**
	 * 属性pk_glzb_b的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPk_glzb_b()
	{
		return pk_glzb_b;
	}

	/**
	 * 属性pk_glzb_b的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPk_glzb_b
	 *            String
	 */
	public void setPk_glzb_b(String newPk_glzb_b)
	{

		pk_glzb_b = newPk_glzb_b;
	}

	 

	/**
	 * 属性cp的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getCp()
	{
		return cp;
	}

	/**
	 * 属性cp的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newCp
	 *            String
	 */
	public void setCp(String newCp)
	{

		cp = newCp;
	}

	/**
	 * 属性xxaglsl的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getXxaglsl()
	{
		return xxaglsl;
	}

	/**
	 * 属性xxaglsl的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newXxaglsl
	 *            Integer
	 */
	public void setXxaglsl(Integer newXxaglsl)
	{

		xxaglsl = newXxaglsl;
	}

	/**
	 * 属性lh的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getLh()
	{
		return lh;
	}

	/**
	 * 属性lh的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newLh
	 *            String
	 */
	public void setLh(String newLh)
	{

		lh = newLh;
	} 
	 
	/**
	 * 属性pk_glzb的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPk_glzb()
	{
		return pk_glzb;
	}

	/**
	 * 属性pk_glzb的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPk_glzb
	 *            String
	 */
	public void setPk_glzb(String newPk_glzb)
	{

		pk_glzb = newPk_glzb;
	}

	/**
	 * 属性clzt的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getClzt()
	{
		return clzt;
	}

	/**
	 * 属性clzt的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newClzt
	 *            Integer
	 */
	public void setClzt(Integer newClzt)
	{

		clzt = newClzt;
	}

	/**
	 * 属性ph的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPh()
	{
		return ph;
	}

	/**
	 * 属性ph的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPh
	 *            String
	 */
	public void setPh(String newPh)
	{

		ph = newPh;
	}

	/**
	 * 属性glyy的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getGlyy()
	{
		return glyy;
	}

	/**
	 * 属性glyy的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newGlyy
	 *            String
	 */
	public void setGlyy(String newGlyy)
	{

		glyy = newGlyy;
	}

	/**
	 * 属性dh的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getDh()
	{
		return dh;
	}

	/**
	 * 属性dh的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newDh
	 *            String
	 */
	public void setDh(String newDh)
	{

		dh = newDh;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException
	{

//		ArrayList errFields = new ArrayList(); // errFields record those null
//
//		// fields that cannot be null.
//		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
//
//		StringBuffer message = new StringBuffer();
//		message.append("下列字段不能为空:");
//		if (errFields.size() > 0)
//		{
//			String[] temp = (String[]) errFields.toArray(new String[0]);
//			message.append(temp[0]);
//			for (int i = 1; i < temp.length; i++)
//			{
//				message.append(",");
//				message.append(temp[i]);
//			}
//			throw new NullFieldException(message.toString());
//		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName()
	{

		return "pk_glzb";

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName()
	{
		return "pk_glzb_b";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName()
	{

		return "mm_glzb_b";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-30
	 */
	public GlItemBVO()
	{

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPk_glzb_b
	 *            主键值
	 */
	public GlItemBVO(String newPk_glzb_b)
	{

		// 为主键字段赋值:
		pk_glzb_b = newPk_glzb_b;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPrimaryKey()
	{

		return pk_glzb_b;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPk_glzb_b
	 *            String
	 */
	public void setPrimaryKey(String newPk_glzb_b)
	{

		pk_glzb_b = newPk_glzb_b;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName()
	{

		return "mm_glzb_b";

	}

	public String getCp_id()
	{
		return cp_id;
	}

	public void setCp_id(String cp_id)
	{
		this.cp_id = cp_id;
	}

	public UFBoolean getSfltd()
	{
		return sfltd;
	}

	public void setSfltd(UFBoolean sfltd)
	{
		this.sfltd = sfltd;
	}

	public String getPk_freeze()
	{
		return pk_freeze;
	}

	public void setPk_freeze(String pk_freeze)
	{
		this.pk_freeze = pk_freeze;
	}

	public String getHwname()
	{
		return hwname;
	}

	public void setHwname(String hwname)
	{
		this.hwname = hwname;
	} 
	public String getCinventoryid() {
		return cinventoryid;
	}

	public void setCinventoryid(String cinventoryid) {
		this.cinventoryid = cinventoryid;
	}
	
	public String getCspaceid() {
		return cspaceid;
	}

	public void setCspaceid(String cspaceid) {
		this.cspaceid = cspaceid;
	}
	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getDinggai() {
		return dinggai;
	}

	public void setDinggai(String dinggai) {
		this.dinggai = dinggai;
	}

	public String getTuopan() {
		return tuopan;
	}

	public void setTuopan(String tuopan) {
		this.tuopan = tuopan;
	}

	public String getDianguanzhi() {
		return dianguanzhi;
	}

	public void setDianguanzhi(String dianguanzhi) {
		this.dianguanzhi = dianguanzhi;
	}
	
	
}
