/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mo.mo6600;

import java.util.ArrayList;

import nc.ui.trade.base.IBillOperate;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2012-7-30
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class GlHeadVO extends SuperVO
{

	private String ks;
	private String scx;
	private String scddh;
	private Integer ddsl;
	private String cp;
	private UFDate xxrq;
	private Integer zdsl;
	private String pk_glzb;
	private Integer ddwgsl;
	private String bz;
	private UFDate phrq;
	private String pghw;
	private Integer djzt;
	private String ck;
	private Integer jyjg;
	private String xxry;
	private Integer ddwwgsl;
	private Integer vbillStatus=0;
	private String pk_corp; 
	private String lrr;
	private String billsign;
	private String forklift; 
    private String billno; 
    private UFTime xxsj;
	private UFDate logindate;//登录日期
	
	
	public static final String KS = "ks";
	public static final String SCX = "scx";
	public static final String SCDDH = "scddh";
	public static final String DDSL = "ddsl";
	public static final String CP = "cp";
	public static final String XXRQ = "xxrq";
	public static final String ZDSL = "zdsl";
	public static final String PK_GLZB = "pk_glzb";
	public static final String DDWGSL = "ddwgsl";
	public static final String BZ = "bz";
	public static final String PHRQ = "phrq";
	public static final String PGHW = "pghw";
	public static final String DJZT = "djzt";
	public static final String CK = "ck";
	public static final String JYJG = "jyjg";
	public static final String XXRY = "xxry";
	public static final String DDWWGSL = "ddwwgsl";
	public static final String DJH = "billno";
	public static final String LoginDate = "logindate";
	public static final String XXSJ="xxsj";
	/**
	 * 属性ks的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getKs()
	{
		return ks;
	}

	/**
	 * 属性ks的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newKs
	 *            String
	 */
	public void setKs(String newKs)
	{

		ks = newKs;
	}

	/**
	 * 属性scx的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getScx()
	{
		return scx;
	}

	/**
	 * 属性scx的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newScx
	 *            String
	 */
	public void setScx(String newScx)
	{

		scx = newScx;
	}

	/**
	 * 属性scddh的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getScddh()
	{
		return scddh;
	}

	/**
	 * 属性scddh的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newScddh
	 *            String
	 */
	public void setScddh(String newScddh)
	{

		scddh = newScddh;
	}

	/**
	 * 属性ddsl的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getDdsl()
	{
		return ddsl;
	}

	/**
	 * 属性ddsl的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newDdsl
	 *            Integer
	 */
	public void setDdsl(Integer newDdsl)
	{

		ddsl = newDdsl;
	}

	/**
	 * 属性cp的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getCp()
	{
		return cp;
	}

	/**
	 * 属性cp的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newCp
	 *            String
	 */
	public void setCp(String newCp)
	{

		cp = newCp;
	}

	/**
	 * 属性xxrq的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Timestamp
	 */
	public UFDate getXxrq()
	{
		return xxrq;
	}

	/**
	 * 属性xxrq的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newXxrq
	 *            Timestamp
	 */
	public void setXxrq(UFDate newXxrq)
	{

		xxrq = newXxrq;
	}

	/**
	 * 属性zdsl的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getZdsl()
	{
		return zdsl;
	}

	/**
	 * 属性zdsl的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newZdsl
	 *            Integer
	 */
	public void setZdsl(Integer newZdsl)
	{

		zdsl = newZdsl;
	}

	 
 

	/**
	 * 属性ddwgsl的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getDdwgsl()
	{
		return ddwgsl;
	}

	/**
	 * 属性ddwgsl的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newDdwgsl
	 *            Integer
	 */
	public void setDdwgsl(Integer newDdwgsl)
	{

		ddwgsl = newDdwgsl;
	}

	/**
	 * 属性bz的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getBz()
	{
		return bz;
	}

	/**
	 * 属性bz的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newBz
	 *            String
	 */
	public void setBz(String newBz)
	{

		bz = newBz;
	}

	/**
	 * 属性phrq的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Timestamp
	 */
	public UFDate getPhrq()
	{
		return phrq;
	}

	/**
	 * 属性phrq的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPhrq
	 *            Timestamp
	 */
	public void setPhrq(UFDate newPhrq)
	{

		phrq = newPhrq;
	}

	/**
	 * 属性pghw的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPghw()
	{
		return pghw;
	}

	/**
	 * 属性pghw的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newPghw
	 *            String
	 */
	public void setPghw(String newPghw)
	{

		pghw = newPghw;
	}

	/**
	 * 属性djzt的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getDjzt()
	{
		return djzt;
	}

	/**
	 * 属性djzt的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newDjzt
	 *            Integer
	 */
	public void setDjzt(Integer newDjzt)
	{

		djzt = newDjzt;
	}

	/**
	 * 属性ck的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getCk()
	{
		return ck;
	}

	/**
	 * 属性ck的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newCk
	 *            String
	 */
	public void setCk(String newCk)
	{

		ck = newCk;
	}

	/**
	 * 属性jyjg的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public Integer getJyjg()
	{
		return jyjg;
	}

	/**
	 * 属性jyjg的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newJyjg
	 *            String
	 */
	public void setJyjg(Integer newJyjg)
	{

		jyjg = newJyjg;
	}

	/**
	 * 属性xxry的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getXxry()
	{
		return xxry;
	}

	/**
	 * 属性xxry的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newXxry
	 *            String
	 */
	public void setXxry(String newXxry)
	{

		xxry = newXxry;
	}

	/**
	 * 属性ddwwgsl的Getter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return Integer
	 */
	public Integer getDdwwgsl()
	{
		return ddwwgsl;
	}

	/**
	 * 属性ddwwgsl的Setter方法.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @param newDdwwgsl
	 *            Integer
	 */
	public void setDdwwgsl(Integer newDdwwgsl)
	{

		ddwwgsl = newDdwwgsl;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException
	{
//
//		ArrayList errFields = new ArrayList(); // errFields record those null
//
//		// fields that cannot be null.
//		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
//
//		StringBuffer message = new StringBuffer();
//		message.append("下列字段不能为空:");
//		if (errFields.size() > 0)
//		{
//			String[] temp = (String[]) errFields.toArray(new String[0]);
//			message.append(temp[0]);
//			for (int i = 1; i < temp.length; i++)
//			{
//				message.append(",");
//				message.append(temp[i]);
//			}
//			throw new NullFieldException(message.toString());
//		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName()
	{

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName()
	{
		return "pk_glzb";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName()
	{

		return "mm_glzb";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2012-7-30
	 */
	public GlHeadVO()
	{

		super();
	}

 

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return String
	 */
	public String getPrimaryKey()
	{

		return pk_glzb;

	}
 

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2012-7-30
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName()
	{

		return "mm_glzb";

	}

	public String getPk_glzb()
	{
		return pk_glzb;
	}

	public void setPk_glzb(String pk_glzb)
	{
		this.pk_glzb = pk_glzb;
	}

	public Integer getVbillStatus()
	{
		if(this.getDjzt()==1)
		{
			return IBillOperate.OP_NO_ADDANDEDIT;
		}
		return 8;
	}

	public void setVbillStatus(Integer vbillStatus)
	{
		this.vbillStatus = vbillStatus;
	}

	public String getPk_corp()
	{
		return pk_corp;
	}

	public void setPk_corp(String pk_corp)
	{
		this.pk_corp = pk_corp;
	}

	public String getLrr()
	{
		return lrr;
	}

	public void setLrr(String lrr)
	{
		this.lrr = lrr;
	}

	public String getBillsign()
	{
		return billsign;
	}

	public void setBillsign(String billsign)
	{
		this.billsign = billsign;
	}

	public String getForklift()
	{
		return forklift;
	}

	public void setForklift(String forklift)
	{
		this.forklift = forklift;
	}
 
	public String getBillno() {
		return billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}
	public UFDate getLogindate() {
		return logindate;
	}

	public void setLogindate(UFDate logindate) {
		this.logindate = logindate;
	}
	
	public UFTime getXxsj() {
		return xxsj;
	}

	public void setXxsj(UFTime xxsj) {
		this.xxsj = xxsj;
	}

}
