/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ic.pub.check;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-08-07 09:12:40
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CHECKVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String vdef9;
	private String pk_check;
	private UFDouble yfmoney;
	private String cinvoiceid;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	private String vordercode;
	private String corderid;
	private String vdef2;
	private String vdef5;
	private UFDouble hxmoney;
	private String vdef3;
	private String vdef6;
	private String vdef4;
	private String vinvoicecode;
	private UFDouble yfbalance;
	private String vdef7;

	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String PK_CHECK = "pk_check";
	public static final String YFMONEY = "yfmoney";
	public static final String CINVOICEID = "cinvoiceid";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String VORDERCODE = "vordercode";
	public static final String CORDERID = "corderid";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String HXMONEY = "hxmoney";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF4 = "vdef4";
	public static final String VINVOICECODE = "vinvoicecode";
	public static final String YFBALANCE = "yfbalance";
	public static final String VDEF7 = "vdef7";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性pk_check的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getPk_check () {
		return pk_check;
	}   
	/**
	 * 属性pk_check的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newPk_check String
	 */
	public void setPk_check (String newPk_check ) {
	 	this.pk_check = newPk_check;
	} 	  
	/**
	 * 属性yfmoney的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return UFDouble
	 */
	public UFDouble getYfmoney () {
		return yfmoney;
	}   
	/**
	 * 属性yfmoney的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newYfmoney UFDouble
	 */
	public void setYfmoney (UFDouble newYfmoney ) {
	 	this.yfmoney = newYfmoney;
	} 	  
	/**
	 * 属性cinvoiceid的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getCinvoiceid () {
		return cinvoiceid;
	}   
	/**
	 * 属性cinvoiceid的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newCinvoiceid String
	 */
	public void setCinvoiceid (String newCinvoiceid ) {
	 	this.cinvoiceid = newCinvoiceid;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vordercode的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVordercode () {
		return vordercode;
	}   
	/**
	 * 属性vordercode的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVordercode String
	 */
	public void setVordercode (String newVordercode ) {
	 	this.vordercode = newVordercode;
	} 	  
	/**
	 * 属性corderid的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getCorderid () {
		return corderid;
	}   
	/**
	 * 属性corderid的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newCorderid String
	 */
	public void setCorderid (String newCorderid ) {
	 	this.corderid = newCorderid;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性hxmoney的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return UFDouble
	 */
	public UFDouble getHxmoney () {
		return hxmoney;
	}   
	/**
	 * 属性hxmoney的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newHxmoney UFDouble
	 */
	public void setHxmoney (UFDouble newHxmoney ) {
	 	this.hxmoney = newHxmoney;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vinvoicecode的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVinvoicecode () {
		return vinvoicecode;
	}   
	/**
	 * 属性vinvoicecode的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVinvoicecode String
	 */
	public void setVinvoicecode (String newVinvoicecode ) {
	 	this.vinvoicecode = newVinvoicecode;
	} 	  
	/**
	 * 属性yfbalance的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return UFDouble
	 */
	public UFDouble getYfbalance () {
		return yfbalance;
	}   
	/**
	 * 属性yfbalance的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newYfbalance UFDouble
	 */
	public void setYfbalance (UFDouble newYfbalance ) {
	 	this.yfbalance = newYfbalance;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2019-08-07 09:12:40
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-08-07 09:12:40
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-08-07 09:12:40
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_check";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-08-07 09:12:40
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "PO_CHECK";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-08-07 09:12:40
	  */
     public CHECKVO() {
		super();	
	}    
} 
