  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.bgjs.jiean;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2012-8-17
 * @author author
 * @version Your Project 1.0
 */
     public class JieanVO extends SuperVO {
           
             public String pk_corp;
             public String icgeneralhid;
             public UFDateTime ts;
             public UFBoolean isyj;
             public UFDouble deffmny;
             public UFDouble yjmny;
             public UFDouble zgmny;
             public Integer dr;
             public String ordercode;
             public String iccode;
             public String pk_jiean;
             public String corderid;
             public String vinvoicecode;
            
             public static final String  PK_CORP="pk_corp";   
             public static final String  ICGENERALHID="icgeneralhid";   
             public static final String  TS="ts";   
             public static final String  ISYJ="isyj";   
             public static final String  DEFFMNY="deffmny";   
             public static final String  YJMNY="yjmny";   
             public static final String  ZGMNY="zgmny";   
             public static final String  DR="dr";   
             public static final String  ORDERCODE="ordercode";   
             public static final String  ICCODE="iccode";   
             public static final String  PK_JIEAN="pk_jiean";   
             public static final String  CORDERID="corderid";   
      
    
        public String getVinvoicecode() {
				return vinvoicecode;
			}

			public void setVinvoicecode(String vinvoicecode) {
				this.vinvoicecode = vinvoicecode;
			}

		/**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性icgeneralhid的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getIcgeneralhid() {
		 return icgeneralhid;
	  }   
	  
     /**
	   * 属性icgeneralhid的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newIcgeneralhid String
	   */
	public void setIcgeneralhid(String newIcgeneralhid) {
		
		icgeneralhid = newIcgeneralhid;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性isyj的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return UFBoolean
	   */
	 public UFBoolean getIsyj() {
		 return isyj;
	  }   
	  
     /**
	   * 属性isyj的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newIsyj UFBoolean
	   */
	public void setIsyj(UFBoolean newIsyj) {
		
		isyj = newIsyj;
	 } 	  
       
        /**
	   * 属性deffmny的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return UFDouble
	   */
	 public UFDouble getDeffmny() {
		 return deffmny;
	  }   
	  
     /**
	   * 属性deffmny的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newDeffmny UFDouble
	   */
	public void setDeffmny(UFDouble newDeffmny) {
		
		deffmny = newDeffmny;
	 } 	  
       
        /**
	   * 属性yjmny的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return UFDouble
	   */
	 public UFDouble getYjmny() {
		 return yjmny;
	  }   
	  
     /**
	   * 属性yjmny的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newYjmny UFDouble
	   */
	public void setYjmny(UFDouble newYjmny) {
		
		yjmny = newYjmny;
	 } 	  
       
        /**
	   * 属性zgmny的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return UFDouble
	   */
	 public UFDouble getZgmny() {
		 return zgmny;
	  }   
	  
     /**
	   * 属性zgmny的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newZgmny UFDouble
	   */
	public void setZgmny(UFDouble newZgmny) {
		
		zgmny = newZgmny;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性ordercode的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getOrdercode() {
		 return ordercode;
	  }   
	  
     /**
	   * 属性ordercode的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newOrdercode String
	   */
	public void setOrdercode(String newOrdercode) {
		
		ordercode = newOrdercode;
	 } 	  
       
        /**
	   * 属性iccode的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getIccode() {
		 return iccode;
	  }   
	  
     /**
	   * 属性iccode的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newIccode String
	   */
	public void setIccode(String newIccode) {
		
		iccode = newIccode;
	 } 	  
       
        /**
	   * 属性pk_jiean的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getPk_jiean() {
		 return pk_jiean;
	  }   
	  
     /**
	   * 属性pk_jiean的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newPk_jiean String
	   */
	public void setPk_jiean(String newPk_jiean) {
		
		pk_jiean = newPk_jiean;
	 } 	  
       
        /**
	   * 属性corderid的Getter方法.
	   *
	   * 创建日期:2012-8-17
	   * @return String
	   */
	 public String getCorderid() {
		 return corderid;
	  }   
	  
     /**
	   * 属性corderid的Setter方法.
	   *
	   * 创建日期:2012-8-17
	   * @param newCorderid String
	   */
	public void setCorderid(String newCorderid) {
		
		corderid = newCorderid;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2012-8-17
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_jiean == null) {
			errFields.add(new String("pk_jiean"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-8-17
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-8-17
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_jiean";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2012-8-17
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "bj_jiean";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-8-17
	  */
	public JieanVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2012-8-17
	 * @param newPk_jiean 主键值
	 */
	 public JieanVO(String newPk_jiean) {
		
		// 为主键字段赋值:
		 pk_jiean = newPk_jiean;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-17
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_jiean;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2012-8-17
	  * @param newPk_jiean  String    
	  */
	 public void setPrimaryKey(String newPk_jiean) {
				
				pk_jiean = newPk_jiean; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2012-8-17
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "bj_jiean"; 
				
	 } 
} 
