package nc.vo.ia.bill;

import java.util.HashMap;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.scm.pub.smart.SmartFieldMeta;
import nc.vo.scm.pub.smart.SmartVOMeta;

public class BillHeaderVOMeta extends SmartVOMeta
{
  private static final long serialVersionUID = -2134611087591815734L;

  public BillHeaderVOMeta()
  {
    init();
  }

  private void init()
  {
    setTable("ia_bill");
    setLabel("ia_bill");
    setPkColName("cbillid");
    SmartFieldMeta sfm = null;
    HashMap hmColumn = new HashMap();

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef4");
    sfm.setColumn("vdef4");
    sfm.setLabel("用户自定义项4");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("fallocflag");
    sfm.setColumn("fallocflag");
    sfm.setLabel("调拨类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("clastoperatorname");
    sfm.setColumn("clastoperatorname");
    sfm.setLabel("操作员名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("coperatorname");
    sfm.setColumn("coperatorname");
    sfm.setLabel("操作员名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cdeptcode");
    sfm.setColumn("cdeptcode");
    sfm.setLabel("部门编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(50);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("ideptattr");
    sfm.setColumn("ideptattr");
    sfm.setLabel("部门属性");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vdispatchname");
    sfm.setColumn("vdispatchname");
    sfm.setLabel("收发");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef3");
    sfm.setColumn("vdef3");
    sfm.setLabel("用户自定义项3");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef2");
    sfm.setColumn("vdef2");
    sfm.setLabel("用户自定义项2");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("coperatorid");
    sfm.setColumn("coperatorid");
    sfm.setLabel("制单人标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("clastoperatorid");
    sfm.setColumn("clastoperatorid");
    sfm.setLabel("最后修改人标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cothercorpid");
    sfm.setColumn("cothercorpid");
    sfm.setLabel("对方公司ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(4);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef1");
    sfm.setColumn("vdef1");
    sfm.setLabel("用户自定义项1");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("voperatorname");
    sfm.setColumn("voperatorname");
    sfm.setLabel("制单人");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(4);
    sfm.setDbType(1);
    sfm.setName("dcheckdate");
    sfm.setColumn("dcheckdate");
    sfm.setLabel("检验日期");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(10);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef10");
    sfm.setColumn("vdef10");
    sfm.setLabel("用户自定义项10");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("fdispatchflag");
    sfm.setColumn("fdispatchflag");
    sfm.setLabel("收发标志");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("dr");
    sfm.setColumn("dr");
    sfm.setLabel("删除标志");
    sfm.setColumnDef(new Integer(0));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("voutcalbodyname");
    sfm.setColumn("voutcalbodyname");
    sfm.setLabel("调出库存组织");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("crdcenterid");
    sfm.setColumn("crdcenterid");
    sfm.setLabel("库存组织标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vbillcode");
    sfm.setColumn("vbillcode");
    sfm.setLabel("单据号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cemployeeid");
    sfm.setColumn("cemployeeid");
    sfm.setLabel("人员标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(4);
    sfm.setDbType(1);
    sfm.setName("dbilldate");
    sfm.setColumn("dbilldate");
    sfm.setLabel("制单日期");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(10);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vemployeename");
    sfm.setColumn("vemployeename");
    sfm.setLabel("人员");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("caccountyear");
    sfm.setColumn("caccountyear");
    sfm.setLabel("会计年度");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(4);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("coutcorpid");
    sfm.setColumn("coutcorpid");
    sfm.setLabel("调出公司ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(4);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbiztypename");
    sfm.setColumn("cbiztypename");
    sfm.setLabel("业务类型名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vagentname");
    sfm.setColumn("vagentname");
    sfm.setLabel("经手人");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vrdcentername");
    sfm.setColumn("vrdcentername");
    sfm.setLabel("库存组织");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbiztypeid");
    sfm.setColumn("cbiztypeid");
    sfm.setLabel("业务类型标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ts");
    sfm.setColumn("ts");
    sfm.setLabel("时间戳");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("tmaketime");
    sfm.setColumn("tmaketime");
    sfm.setLabel("制单时间");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("tlastmaketime");
    sfm.setColumn("tlastmaketime");
    sfm.setLabel("最后修改时间");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cwarehousemanagerid");
    sfm.setColumn("cwarehousemanagerid");
    sfm.setLabel("库管员标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vcheckbillcode");
    sfm.setColumn("vcheckbillcode");
    sfm.setLabel("检验单号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_areacl");
    sfm.setColumn("pk_areacl");
    sfm.setLabel("地区分类主键");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vcustomvendorname");
    sfm.setColumn("vcustomvendorname");
    sfm.setLabel("客商");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("ncost");
    sfm.setColumn("ncost");
    sfm.setLabel("组装成本");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bestimateflag");
    sfm.setColumn("bestimateflag");
    sfm.setLabel("是否暂估");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ccustomvendorid");
    sfm.setColumn("ccustomvendorid");
    sfm.setLabel("客商标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cdispatchid");
    sfm.setColumn("cdispatchid");
    sfm.setLabel("收发标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bcalculatedinvcost");
    sfm.setColumn("bcalculatedinvcost");
    sfm.setLabel("存货是否成本计算");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bingathersettle");
    sfm.setColumn("bingathersettle");
    sfm.setLabel("调入仓库是否汇总结算");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("boutgathersettle");
    sfm.setColumn("boutgathersettle");
    sfm.setLabel("调出仓库是否汇总结算");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csourcemodulename");
    sfm.setColumn("csourcemodulename");
    sfm.setLabel("来源模块");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(3);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vnote");
    sfm.setColumn("vnote");
    sfm.setLabel("备注");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(120);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbilltypecode");
    sfm.setColumn("cbilltypecode");
    sfm.setLabel("单据类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cothercalbodyid");
    sfm.setColumn("cothercalbodyid");
    sfm.setLabel("对方库存组织PK");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cotherwarehouseid");
    sfm.setColumn("cotherwarehouseid");
    sfm.setLabel("对方仓库PK");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bdisableflag");
    sfm.setColumn("bdisableflag");
    sfm.setLabel("是否作废");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csqlclause");
    sfm.setColumn("csqlclause");
    sfm.setLabel("SQL语句");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1000);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bwithdrawalflag");
    sfm.setColumn("bwithdrawalflag");
    sfm.setLabel("是否假退料");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("coutcalbodyid");
    sfm.setColumn("coutcalbodyid");
    sfm.setLabel("调出库存组织ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cagentid");
    sfm.setColumn("cagentid");
    sfm.setLabel("经手人标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbillid");
    sfm.setColumn("cbillid");
    sfm.setLabel("单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vstockrdcentername");
    sfm.setColumn("vstockrdcentername");
    sfm.setLabel("仓储库存组织");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bauditedflag");
    sfm.setColumn("bauditedflag");
    sfm.setLabel("是否审核");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbusinessbillid");
    sfm.setColumn("cbusinessbillid");
    sfm.setLabel("对应业务单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_corp");
    sfm.setColumn("pk_corp");
    sfm.setLabel("公司主键");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(4);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vbiztypename");
    sfm.setColumn("vbiztypename");
    sfm.setLabel("业务类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vwarehousename");
    sfm.setColumn("vwarehousename");
    sfm.setLabel("仓库");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cstockrdcenterid");
    sfm.setColumn("cstockrdcenterid");
    sfm.setLabel("仓储库存组织标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cdeptid");
    sfm.setColumn("cdeptid");
    sfm.setLabel("部门标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vdeptname");
    sfm.setColumn("vdeptname");
    sfm.setLabel("部门");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cwarehouseid");
    sfm.setColumn("cwarehouseid");
    sfm.setLabel("仓库标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(4);
    sfm.setName("iprintcount");
    sfm.setColumn("iprintcount");
    sfm.setLabel("打印次数");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef9");
    sfm.setColumn("vdef9");
    sfm.setLabel("用户自定义项9");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vwarehousemanagername");
    sfm.setColumn("vwarehousemanagername");
    sfm.setLabel("库管员");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef8");
    sfm.setColumn("vdef8");
    sfm.setLabel("用户自定义项8");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ccustombasid");
    sfm.setColumn("ccustombasid");
    sfm.setLabel("客商基本档案");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef7");
    sfm.setColumn("vdef7");
    sfm.setLabel("用户自定义项7");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef6");
    sfm.setColumn("vdef6");
    sfm.setLabel("用户自定义项6");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vadjpricefilecode");
    sfm.setColumn("vadjpricefilecode");
    sfm.setLabel("调价文件号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(50);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("caccountmonth");
    sfm.setColumn("caccountmonth");
    sfm.setLabel("会计月份");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef5");
    sfm.setColumn("vdef5");
    sfm.setLabel("用户自定义项5");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef11");
    sfm.setColumn("vdef11");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef12");
    sfm.setColumn("vdef12");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef13");
    sfm.setColumn("vdef13");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef14");
    sfm.setColumn("vdef14");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef15");
    sfm.setColumn("vdef15");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef16");
    sfm.setColumn("vdef16");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef17");
    sfm.setColumn("vdef17");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef18");
    sfm.setColumn("vdef18");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef19");
    sfm.setColumn("vdef19");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef20");
    sfm.setColumn("vdef20");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc1");
    sfm.setColumn("pk_defdoc1");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc2");
    sfm.setColumn("pk_defdoc2");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc3");
    sfm.setColumn("pk_defdoc3");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc4");
    sfm.setColumn("pk_defdoc4");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc5");
    sfm.setColumn("pk_defdoc5");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc6");
    sfm.setColumn("pk_defdoc6");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc7");
    sfm.setColumn("pk_defdoc7");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc8");
    sfm.setColumn("pk_defdoc8");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc9");
    sfm.setColumn("pk_defdoc9");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc10");
    sfm.setColumn("pk_defdoc10");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc11");
    sfm.setColumn("pk_defdoc11");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc12");
    sfm.setColumn("pk_defdoc12");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc13");
    sfm.setColumn("pk_defdoc13");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc14");
    sfm.setColumn("pk_defdoc14");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc15");
    sfm.setColumn("pk_defdoc15");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc16");
    sfm.setColumn("pk_defdoc16");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc17");
    sfm.setColumn("pk_defdoc17");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc18");
    sfm.setColumn("pk_defdoc18");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc19");
    sfm.setColumn("pk_defdoc19");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc20");
    sfm.setColumn("pk_defdoc20");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    setColumns(hmColumn);
  }
}