package nc.vo.ia.bill;

import java.util.HashMap;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.scm.pub.smart.SmartFieldMeta;
import nc.vo.scm.pub.smart.SmartVOMeta;

public class BillItemVOMeta extends SmartVOMeta
{
  private static final long serialVersionUID = 1965149775030663861L;

  public BillItemVOMeta()
  {
    init();
  }

  private void init()
  {
    setTable("ia_bill_b");
    setLabel("ia_bill_b");
    setPkColName("cbill_bid");
    SmartFieldMeta sfm = null;
    HashMap hmColumn = new HashMap();

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfirstbilltypecode");
    sfm.setColumn("cfirstbilltypecode");
    sfm.setLabel("源头单据类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("dr");
    sfm.setColumn("dr");
    sfm.setLabel("删除标志");
    sfm.setColumnDef(new Integer(0));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csourcebillitemid");
    sfm.setColumn("csourcebillitemid");
    sfm.setLabel("来源单据分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventoryid");
    sfm.setColumn("cinventoryid");
    sfm.setLabel("存货标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventorycode");
    sfm.setColumn("cinventorycode");
    sfm.setLabel("存货编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vsourcerowno");
    sfm.setColumn("vsourcerowno");
    sfm.setLabel("来源单据行号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bretractflag");
    sfm.setColumn("bretractflag");
    sfm.setLabel("退货标志");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("btransferincometax");
    sfm.setColumn("btransferincometax");
    sfm.setLabel("是否进项税转出");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cadjustbillid");
    sfm.setColumn("cadjustbillid");
    sfm.setLabel("调整单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfacardid");
    sfm.setColumn("cfacardid");
    sfm.setLabel("固定资产卡片ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventorytype");
    sfm.setColumn("cinventorytype");
    sfm.setLabel("型号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("noriginalprice");
    sfm.setColumn("noriginalprice");
    sfm.setLabel("调整前单价");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("foutadjustableflag");
    sfm.setColumn("foutadjustableflag");
    sfm.setLabel("出库是否可调整标志");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfadevicecode");
    sfm.setColumn("cfadevicecode");
    sfm.setLabel("固定资产附属设备编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vofas");
    sfm.setColumn("vofas");
    sfm.setLabel("固定资产接口");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventoryspec");
    sfm.setColumn("cinventoryspec");
    sfm.setLabel("规格");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(4);
    sfm.setDbType(1);
    sfm.setName("dbizdate");
    sfm.setColumn("dbizdate");
    sfm.setLabel("业务日期");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(10);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vbatch");
    sfm.setColumn("vbatch");
    sfm.setLabel("批次号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbill_bid");
    sfm.setColumn("cbill_bid");
    sfm.setLabel("分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cicitemid");
    sfm.setColumn("cicitemid");
    sfm.setLabel("IC子表ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cauditorid");
    sfm.setColumn("cauditorid");
    sfm.setLabel("审核人标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinvclid");
    sfm.setColumn("cinvclid");
    sfm.setLabel("存货分类");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nsimulatemny");
    sfm.setColumn("nsimulatemny");
    sfm.setLabel("模拟成本");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(4);
    sfm.setName("iauditsequence");
    sfm.setColumn("iauditsequence");
    sfm.setLabel("审核序号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vbillcode");
    sfm.setColumn("vbillcode");
    sfm.setLabel("单据号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("cicbillcode");
    sfm.setColumn("cicbillcode");
    sfm.setLabel("IC单据号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cadjustbillitemid");
    sfm.setColumn("cadjustbillitemid");
    sfm.setLabel("调整单据分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csumrtvouchid");
    sfm.setColumn("csumrtvouchid");
    sfm.setLabel("汇总凭证ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nchangerate");
    sfm.setColumn("nchangerate");
    sfm.setLabel("换算率");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vastunitname");
    sfm.setColumn("vastunitname");
    sfm.setLabel("辅计量单位");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectphase");
    sfm.setColumn("cprojectphase");
    sfm.setLabel("项目阶段");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("blargessflag");
    sfm.setColumn("blargessflag");
    sfm.setLabel("是否赠品");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfirstbillcode");
    sfm.setColumn("vfirstbillcode");
    sfm.setLabel("源头单据号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("ninvarymny");
    sfm.setColumn("ninvarymny");
    sfm.setLabel("收入差异");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinbillitemid");
    sfm.setColumn("cinbillitemid");
    sfm.setLabel("对应入库单分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nsettledsendnum");
    sfm.setColumn("nsettledsendnum");
    sfm.setLabel("累计发出数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nadjustnum");
    sfm.setColumn("nadjustnum");
    sfm.setLabel("调整数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vbomcodename");
    sfm.setColumn("vbomcodename");
    sfm.setLabel("成本对象名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vsourcebillcode");
    sfm.setColumn("vsourcebillcode");
    sfm.setLabel("来源单据号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbilltypecode");
    sfm.setColumn("cbilltypecode");
    sfm.setLabel("单据类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cicbilltype");
    sfm.setColumn("cicbilltype");
    sfm.setLabel("IC单据类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nincometax");
    sfm.setColumn("nincometax");
    sfm.setLabel("进项税率");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nexpaybacktax");
    sfm.setColumn("nexpaybacktax");
    sfm.setLabel("退税率");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(15);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_corp");
    sfm.setColumn("pk_corp");
    sfm.setLabel("公司主键");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(4);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("ddrawrate");
    sfm.setColumn("ddrawrate");
    sfm.setLabel("提取比例");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(6);
    sfm.setLength(9);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfirstbillid");
    sfm.setColumn("cfirstbillid");
    sfm.setLabel("源头单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("folddatagetmodelflag");
    sfm.setColumn("folddatagetmodelflag");
    sfm.setLabel("成本计算前数据获得方式");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectphasename");
    sfm.setColumn("cprojectphasename");
    sfm.setLabel("项目阶段名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ccrspbillitemid");
    sfm.setColumn("ccrspbillitemid");
    sfm.setLabel("对应业务单据分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventorymeasname");
    sfm.setColumn("cinventorymeasname");
    sfm.setLabel("单位名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csaleadviceid");
    sfm.setColumn("csaleadviceid");
    sfm.setLabel("销售系统出库单标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("ndrawsummny");
    sfm.setColumn("ndrawsummny");
    sfm.setLabel("累计提取金额");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cbillid");
    sfm.setColumn("cbillid");
    sfm.setLabel("单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cicbillid");
    sfm.setColumn("cicbillid");
    sfm.setLabel("IC主表ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectname");
    sfm.setColumn("cprojectname");
    sfm.setLabel("项目名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ccsaleadviceitemid");
    sfm.setColumn("ccsaleadviceitemid");
    sfm.setLabel("销售系统出库单分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinvkind");
    sfm.setColumn("cinvkind");
    sfm.setLabel("存货属性");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("bauditbatchflag");
    sfm.setColumn("bauditbatchflag");
    sfm.setLabel("是否批次核算");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cauditorname");
    sfm.setColumn("cauditorname");
    sfm.setLabel("审核人名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("brtvouchflag");
    sfm.setColumn("brtvouchflag");
    sfm.setLabel("是否已生成实时凭证");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("fdatagetmodelflag");
    sfm.setColumn("fdatagetmodelflag");
    sfm.setLabel("数据获得方式");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cdatagetmodelname");
    sfm.setColumn("cdatagetmodelname");
    sfm.setLabel("数据获得方式名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("cwp");
    sfm.setColumn("cwp");
    sfm.setLabel("工序");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cwpname");
    sfm.setColumn("cwpname");
    sfm.setLabel("工序名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("fpricemodeflag");
    sfm.setColumn("fpricemodeflag");
    sfm.setLabel("计价方式编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cpricemodename");
    sfm.setColumn("cpricemodename");
    sfm.setLabel("计价方式名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef6");
    sfm.setColumn("vdef6");
    sfm.setLabel("用户自定义项6");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef5");
    sfm.setColumn("vdef5");
    sfm.setLabel("用户自定义项5");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cinventoryname");
    sfm.setColumn("cinventoryname");
    sfm.setLabel("存货名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef4");
    sfm.setColumn("vdef4");
    sfm.setLabel("用户自定义项4");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef3");
    sfm.setColumn("vdef3");
    sfm.setLabel("用户自定义项3");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef2");
    sfm.setColumn("vdef2");
    sfm.setLabel("用户自定义项2");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef1");
    sfm.setColumn("vdef1");
    sfm.setLabel("用户自定义项1");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectid");
    sfm.setColumn("cprojectid");
    sfm.setLabel("项目标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfadevicename");
    sfm.setColumn("cfadevicename");
    sfm.setLabel("固定资产附属设备名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vbomcodecode");
    sfm.setColumn("vbomcodecode");
    sfm.setLabel("成本对象编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nprice");
    sfm.setColumn("nprice");
    sfm.setLabel("单价");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("ts");
    sfm.setColumn("ts");
    sfm.setLabel("时间戳");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cvendorid");
    sfm.setColumn("cvendorid");
    sfm.setLabel("供应商");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nsettledretractnum");
    sfm.setColumn("nsettledretractnum");
    sfm.setLabel("累计冲回数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfirstbillitemid");
    sfm.setColumn("cfirstbillitemid");
    sfm.setLabel("源头单据分录标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csaleaudititemid");
    sfm.setColumn("csaleaudititemid");
    sfm.setLabel("销售结算明细标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nplanedmny");
    sfm.setColumn("nplanedmny");
    sfm.setLabel("计划金额");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vofree");
    sfm.setColumn("vofree");
    sfm.setLabel("自由项vo");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csqlclause");
    sfm.setColumn("csqlclause");
    sfm.setLabel("SQL语句");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1000);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfirstrowno");
    sfm.setColumn("vfirstrowno");
    sfm.setLabel("源头单据行号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree5");
    sfm.setColumn("vfree5");
    sfm.setLabel("自由项5");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree4");
    sfm.setColumn("vfree4");
    sfm.setLabel("自由项4");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree3");
    sfm.setColumn("vfree3");
    sfm.setLabel("自由项3");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree2");
    sfm.setColumn("vfree2");
    sfm.setLabel("自由项2");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("castunitid");
    sfm.setColumn("castunitid");
    sfm.setLabel("辅计量单位");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree1");
    sfm.setColumn("vfree1");
    sfm.setLabel("自由项1");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vfree0");
    sfm.setColumn("vfree0");
    sfm.setLabel("自由项");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nassistnum");
    sfm.setColumn("nassistnum");
    sfm.setLabel("辅计量数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectphasecode");
    sfm.setColumn("cprojectphasecode");
    sfm.setLabel("项目阶段编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("castunitname");
    sfm.setColumn("castunitname");
    sfm.setLabel("辅计量名称");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(4);
    sfm.setDbType(1);
    sfm.setName("dauditdate");
    sfm.setColumn("dauditdate");
    sfm.setLabel("审核日期");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(10);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("noutvarymny");
    sfm.setColumn("noutvarymny");
    sfm.setLabel("发出差异");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vprojectname");
    sfm.setColumn("vprojectname");
    sfm.setLabel("项目");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vvendorname");
    sfm.setColumn("vvendorname");
    sfm.setLabel("供应商");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cprojectcode");
    sfm.setColumn("cprojectcode");
    sfm.setLabel("项目编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cfadeviceid");
    sfm.setColumn("cfadeviceid");
    sfm.setLabel("固定资产附属设备ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nnumber");
    sfm.setColumn("nnumber");
    sfm.setLabel("数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nplanedprice");
    sfm.setColumn("nplanedprice");
    sfm.setLabel("计划单价");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vproducebatch");
    sfm.setColumn("vproducebatch");
    sfm.setLabel("生产批号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(30);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csourcebillid");
    sfm.setColumn("csourcebillid");
    sfm.setLabel("来源单据标识");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vbomcode");
    sfm.setColumn("vbomcode");
    sfm.setLabel("成本对象");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("csourcebilltypecode");
    sfm.setColumn("csourcebilltypecode");
    sfm.setLabel("来源单据类型");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(2);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nmoney");
    sfm.setColumn("nmoney");
    sfm.setLabel("金额");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(0);
    sfm.setDbType(1);
    sfm.setName("badjusteditemflag");
    sfm.setColumn("badjusteditemflag");
    sfm.setLabel("是否调整了分录标志");
    sfm.setColumnDef(new UFBoolean(false));
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(1);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("vauditorname");
    sfm.setColumn("vauditorname");
    sfm.setLabel("审核人");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(2);
    sfm.setDbType(5);
    sfm.setName("irownumber");
    sfm.setColumn("irownumber");
    sfm.setLabel("行号");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(0);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cvoucherid");
    sfm.setColumn("cvoucherid");
    sfm.setLabel("会计凭证ID");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("cwpcode");
    sfm.setColumn("cwpcode");
    sfm.setLabel("工序编码");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef7");
    sfm.setColumn("vdef7");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef8");
    sfm.setColumn("vdef8");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef9");
    sfm.setColumn("vdef9");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef10");
    sfm.setColumn("vdef10");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef11");
    sfm.setColumn("vdef11");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef12");
    sfm.setColumn("vdef12");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef13");
    sfm.setColumn("vdef13");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef14");
    sfm.setColumn("vdef14");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef15");
    sfm.setColumn("vdef15");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef16");
    sfm.setColumn("vdef16");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef17");
    sfm.setColumn("vdef17");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef18");
    sfm.setColumn("vdef18");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef19");
    sfm.setColumn("vdef19");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("vdef20");
    sfm.setColumn("vdef20");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc1");
    sfm.setColumn("pk_defdoc1");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc2");
    sfm.setColumn("pk_defdoc2");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc3");
    sfm.setColumn("pk_defdoc3");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc4");
    sfm.setColumn("pk_defdoc4");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc5");
    sfm.setColumn("pk_defdoc5");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc6");
    sfm.setColumn("pk_defdoc6");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc7");
    sfm.setColumn("pk_defdoc7");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc8");
    sfm.setColumn("pk_defdoc8");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc9");
    sfm.setColumn("pk_defdoc9");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc10");
    sfm.setColumn("pk_defdoc10");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc11");
    sfm.setColumn("pk_defdoc11");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc12");
    sfm.setColumn("pk_defdoc12");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc13");
    sfm.setColumn("pk_defdoc13");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc14");
    sfm.setColumn("pk_defdoc14");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc15");
    sfm.setColumn("pk_defdoc15");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc16");
    sfm.setColumn("pk_defdoc16");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc17");
    sfm.setColumn("pk_defdoc17");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc18");
    sfm.setColumn("pk_defdoc18");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc19");
    sfm.setColumn("pk_defdoc19");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(12);
    sfm.setName("pk_defdoc20");
    sfm.setColumn("pk_defdoc20");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(100);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_reqcorp");
    sfm.setColumn("pk_reqcorp");
    sfm.setLabel("需求公司");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_reqstoorg");
    sfm.setColumn("pk_reqstoorg");
    sfm.setLabel("需求库存组织");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_creqwareid");
    sfm.setColumn("pk_creqwareid");
    sfm.setLabel("需求仓库");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(3);
    sfm.setDbType(1);
    sfm.setName("pk_invoicecorp");
    sfm.setColumn("pk_invoicecorp");
    sfm.setLabel("收票公司");
    sfm.setColumnDef(null);
    sfm.setAllowNull(true);
    sfm.setPrecision(0);
    sfm.setLength(20);
    sfm.setPersistence(false);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nreasonalwastmny");
    sfm.setColumn("nreasonalwastmny");
    sfm.setLabel("合理损耗金额");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nreasonalwastnum");
    sfm.setColumn("nreasonalwastnum");
    sfm.setLabel("合理损耗数量");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    sfm = new SmartFieldMeta();
    sfm.setType(1);
    sfm.setDbType(2);
    sfm.setName("nreasonalwastprice");
    sfm.setColumn("nreasonalwastprice");
    sfm.setLabel("合理损耗单价");
    sfm.setColumnDef(null);
    sfm.setAllowNull(false);
    sfm.setPrecision(8);
    sfm.setLength(20);
    sfm.setPersistence(true);
    hmColumn.put(sfm.getName(), sfm);

    setColumns(hmColumn);
  }
}