/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.by.invapp.h0h003;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2012-07-20 13:58:54
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class InvContrastdocVO extends SuperVO {
	private String pk_corp;
	private String ts;
	private Integer dr;
	private String memo;
	private String pk_invcontrastdoc;
	private String invcode;
	private String invname;
	private String invspec;
	private String invtype;
	private String pk_invcl;
	private String pk_invbasdoc;
	private String invclasscode;
	private String invclassname;
	private String oldinvcode;
	private String oldinvname;
	private String oldinvspec;
	private String oldinvtype;
	private String vdef1;
	private String vdef2;
	private String vdef3;
	private String vdef4;
	private String vdef5;
	
 
	public String getPk_invbasdoc() {
		return pk_invbasdoc;
	}

	public void setPk_invbasdoc(String pk_invbasdoc) {
		this.pk_invbasdoc = pk_invbasdoc;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getTs() {
		return ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getPk_invcontrastdoc() {
		return pk_invcontrastdoc;
	}

	public void setPk_invcontrastdoc(String pk_invcontrastdoc) {
		this.pk_invcontrastdoc = pk_invcontrastdoc;
	}

	public String getInvcode() {
		return invcode;
	}

	public void setInvcode(String invcode) {
		this.invcode = invcode;
	}

	public String getInvname() {
		return invname;
	}

	public void setInvname(String invname) {
		this.invname = invname;
	}

	public String getInvspec() {
		return invspec;
	}

	public void setInvspec(String invspec) {
		this.invspec = invspec;
	}

	public String getInvtype() {
		return invtype;
	}

	public void setInvtype(String invtype) {
		this.invtype = invtype;
	}

	public String getPk_invcl() {
		return pk_invcl;
	}

	public void setPk_invcl(String pk_invcl) {
		this.pk_invcl = pk_invcl;
	}

	public String getInvclasscode() {
		return invclasscode;
	}

	public void setInvclasscode(String invclasscode) {
		this.invclasscode = invclasscode;
	}

	public String getInvclassname() {
		return invclassname;
	}

	public void setInvclassname(String invclassname) {
		this.invclassname = invclassname;
	}

	public String getOldinvcode() {
		return oldinvcode;
	}

	public void setOldinvcode(String oldinvcode) {
		this.oldinvcode = oldinvcode;
	}

	public String getOldinvname() {
		return oldinvname;
	}

	public void setOldinvname(String oldinvname) {
		this.oldinvname = oldinvname;
	}

	public String getOldinvspec() {
		return oldinvspec;
	}

	public void setOldinvspec(String oldinvspec) {
		this.oldinvspec = oldinvspec;
	}

	public String getOldinvtype() {
		return oldinvtype;
	}

	public void setOldinvtype(String oldinvtype) {
		this.oldinvtype = oldinvtype;
	}

	public String getVdef1() {
		return vdef1;
	}

	public void setVdef1(String vdef1) {
		this.vdef1 = vdef1;
	}

	public String getVdef2() {
		return vdef2;
	}

	public void setVdef2(String vdef2) {
		this.vdef2 = vdef2;
	}

	public String getVdef3() {
		return vdef3;
	}

	public void setVdef3(String vdef3) {
		this.vdef3 = vdef3;
	}

	public String getVdef4() {
		return vdef4;
	}

	public void setVdef4(String vdef4) {
		this.vdef4 = vdef4;
	}

	public String getVdef5() {
		return vdef5;
	}

	public void setVdef5(String vdef5) {
		this.vdef5 = vdef5;
	}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-07-20 13:58:54
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-07-20 13:58:54
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_invcontrastdoc";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2012-07-20 13:58:54
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "bd_invcontrastdoc";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-07-20 13:58:54
	  */
     public InvContrastdocVO() {
		super();	
	}    
} 
