/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.by.invapp.h0h004;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDouble;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2012-07-20 13:58:54
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class IchandnumVO extends SuperVO {
	private String pk_corp;
	private String ts;
	private Integer dr;
	private String memo;
	private String bodycode;
	private String bodyname;
	private String invcode;
	private String invname;
	private String storcode;
	private String storname;
	private String cscode;
	private String csname;
	private String vbatchcode;
	private String dbizdate;
	private String vfree1;
	private String custcode;
	private UFDouble ninnum;
	private UFDouble oldninnum;
	private UFDouble nmny;
	private UFDouble oldnmny;
	private String vdef1;
	private String vdef2;
	private String vdef3;
	private String vdef4;
	private String vdef5;
	

	public String getDbizdate() {
		return dbizdate;
	}

	public void setDbizdate(String dbizdate) {
		this.dbizdate = dbizdate;
	}

	public UFDouble getNinnum() {
		return ninnum;
	}

	public void setNinnum(UFDouble ninnum) {
		this.ninnum = ninnum;
	}

	public String getPk_corp() {
		return pk_corp;
	}

	public void setPk_corp(String pk_corp) {
		this.pk_corp = pk_corp;
	}

	public String getTs() {
		return ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getBodycode() {
		return bodycode;
	}

	public void setBodycode(String bodycode) {
		this.bodycode = bodycode;
	}

	public String getBodyname() {
		return bodyname;
	}

	public void setBodyname(String bodyname) {
		this.bodyname = bodyname;
	}

	public String getInvcode() {
		return invcode;
	}

	public void setInvcode(String invcode) {
		this.invcode = invcode;
	}

	public String getInvname() {
		return invname;
	}

	public void setInvname(String invname) {
		this.invname = invname;
	}

	public String getStorcode() {
		return storcode;
	}

	public void setStorcode(String storcode) {
		this.storcode = storcode;
	}

	public String getStorname() {
		return storname;
	}

	public void setStorname(String storname) {
		this.storname = storname;
	}

	public String getCscode() {
		return cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getCsname() {
		return csname;
	}

	public void setCsname(String csname) {
		this.csname = csname;
	}

	public String getVbatchcode() {
		return vbatchcode;
	}

	public void setVbatchcode(String vbatchcode) {
		this.vbatchcode = vbatchcode;
	}

	public String getVfree1() {
		return vfree1;
	}

	public void setVfree1(String vfree1) {
		this.vfree1 = vfree1;
	}

	public String getCustcode() {
		return custcode;
	}

	public void setCustcode(String custcode) {
		this.custcode = custcode;
	}

	public UFDouble getOldninnum() {
		return oldninnum;
	}

	public void setOldninnum(UFDouble oldninnum) {
		this.oldninnum = oldninnum;
	}

	public UFDouble getNmny() {
		return nmny;
	}

	public void setNmny(UFDouble nmny) {
		this.nmny = nmny;
	}

	public UFDouble getOldnmny() {
		return oldnmny;
	}

	public void setOldnmny(UFDouble oldnmny) {
		this.oldnmny = oldnmny;
	}

	public String getVdef1() {
		return vdef1;
	}

	public void setVdef1(String vdef1) {
		this.vdef1 = vdef1;
	}

	public String getVdef2() {
		return vdef2;
	}

	public void setVdef2(String vdef2) {
		this.vdef2 = vdef2;
	}

	public String getVdef3() {
		return vdef3;
	}

	public void setVdef3(String vdef3) {
		this.vdef3 = vdef3;
	}

	public String getVdef4() {
		return vdef4;
	}

	public void setVdef4(String vdef4) {
		this.vdef4 = vdef4;
	}

	public String getVdef5() {
		return vdef5;
	}

	public void setVdef5(String vdef5) {
		this.vdef5 = vdef5;
	}

	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2012-07-20 13:58:54
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2012-07-20 13:58:54
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return null;
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2012-07-20 13:58:54
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return null;
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2012-07-20 13:58:54
	  */
     public IchandnumVO() {
		super();	
	}    
} 
