  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.arap.h101;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-9-9
 * @author author
 * @version Your Project 1.0
 */
     public class FksqdBVO extends SuperVO {
           
             public String pk_corp;
             public UFDouble dfbbsj;
             public String pk_sybm;
             public String pk_jsfs;
             public String vdef4;
             public String pk_wldx;
             public String pk_szxm;
             public UFDouble ybye;
             public String fph;
             public UFDouble dfybje;
             public Integer dr;
             public UFDouble bbhl;
             public String pk_zx;
             public UFDouble bbye;
             public String gyskhh;
             public String xh;
             public String zy;
             public UFDouble dfbbwsje;
             public String ts;
             public String zyx16;
             public UFDouble dfsl;
             public UFDouble hsdj;
             public String pk_ch;
             public String pk_fksqd;
             public String qxrq;
             public String skyhzh;
             public String pk_xjllxm;
             public UFDouble dfybsj;
             public String kslb;
             public String pk_gys;
             public String vdef3;
             public String pk_ks;
             public String pk_bz;
             public UFDouble ysje;
             public UFDouble dffbje;
             public String vdef10;
             public String vdef5;
             public String pk_xmmc;
             public String pk_fksqd_b;
             public String pk_zxxm;
             public String fkyhzh;
             public String vdef7;
             public String pk_km;
             public String vdef2;
             public UFDouble dffbwsje;
             public String vmemo;
             public UFDouble dfybwsje;
             public String vdef1;
             public UFDouble dfbbje;
             public String gg;
             public UFDouble sl;
             public UFDouble dffbsj;
             public UFDouble fbye;
             public String pk_ywy;
             public String vdef9;
             public UFDouble fbhl;
             public String vdef8;
             public String pk_sfkxy;
             public String pk_bm;
             public String vdef6;
             public String ysdbh;
             public String pk_zfr;
             public String ddh;
             public String yfdzbzj;//应付单子表主键
                	         
             public static final String  PK_CORP="pk_corp";   
             public static final String  DFBBSJ="dfbbsj";   
             public static final String  PK_SYBM="pk_sybm";   
             public static final String  PK_JSFS="pk_jsfs";   
             public static final String  VDEF4="vdef4";   
             public static final String  PK_WLDX="pk_wldx";   
             public static final String  PK_SZXM="pk_szxm";   
             public static final String  YBYE="ybye";   
             public static final String  FPH="fph";   
             public static final String  DFYBJE="dfybje";   
             public static final String  DR="dr";   
             public static final String  BBHL="bbhl";   
             public static final String  PK_ZX="pk_zx";   
             public static final String  BBYE="bbye";   
             public static final String  GYSKHH="gyskhh";   
             public static final String  XH="xh";   
             public static final String  ZY="zy";   
             public static final String  DFBBWSJE="dfbbwsje";   
             public static final String  TS="ts";   
             public static final String  ZYX16="zyx16";   
             public static final String  DFSL="dfsl";   
             public static final String  HSDJ="hsdj";   
             public static final String  PK_CH="pk_ch";   
             public static final String  PK_FKSQD="pk_fksqd";   
             public static final String  QXRQ="qxrq";   
             public static final String  SKYHZH="skyhzh";   
             public static final String  PK_XJLLXM="pk_xjllxm";   
             public static final String  DFYBSJ="dfybsj";   
             public static final String  KSLB="kslb";   
             public static final String  PK_GYS="pk_gys";   
             public static final String  VDEF3="vdef3";   
             public static final String  PK_KS="pk_ks";   
             public static final String  PK_BZ="pk_bz";   
             public static final String  YSJE="ysje";   
             public static final String  DFFBJE="dffbje";   
             public static final String  VDEF10="vdef10";   
             public static final String  VDEF5="vdef5";   
             public static final String  PK_XMMC="pk_xmmc";   
             public static final String  PK_FKSQD_B="pk_fksqd_b";   
             public static final String  PK_ZXXM="pk_zxxm";   
             public static final String  FKYHZH="fkyhzh";   
             public static final String  VDEF7="vdef7";   
             public static final String  PK_KM="pk_km";   
             public static final String  VDEF2="vdef2";   
             public static final String  DFFBWSJE="dffbwsje";   
             public static final String  VMEMO="vmemo";   
             public static final String  DFYBWSJE="dfybwsje";   
             public static final String  VDEF1="vdef1";   
             public static final String  DFBBJE="dfbbje";   
             public static final String  GG="gg";   
             public static final String  SL="sl";   
             public static final String  DFFBSJ="dffbsj";   
             public static final String  FBYE="fbye";   
             public static final String  PK_YWY="pk_ywy";   
             public static final String  VDEF9="vdef9";   
             public static final String  FBHL="fbhl";   
             public static final String  VDEF8="vdef8";   
             public static final String  PK_SFKXY="pk_sfkxy";   
             public static final String  PK_BM="pk_bm";   
             public static final String  VDEF6="vdef6";   
             public static final String  YSDBH="ysdbh";   
             public static final String  PK_ZFR="pk_zfr";   
             public static final String  DDH="ddh";     
             public static final String  YFDZBZJ="yfdzbzj";  
             
    
        public String getYfdzbzj() {
				return yfdzbzj;
			}

			public void setYfdzbzj(String yfdzbzj) {
				this.yfdzbzj = yfdzbzj;
			}

		/**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性dfbbsj的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfbbsj() {
		 return dfbbsj;
	  }   
	  
     /**
	   * 属性dfbbsj的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfbbsj UFDouble
	   */
	public void setDfbbsj(UFDouble newDfbbsj) {
		
		dfbbsj = newDfbbsj;
	 } 	  
       
        /**
	   * 属性pk_sybm的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_sybm() {
		 return pk_sybm;
	  }   
	  
     /**
	   * 属性pk_sybm的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_sybm String
	   */
	public void setPk_sybm(String newPk_sybm) {
		
		pk_sybm = newPk_sybm;
	 } 	  
       
        /**
	   * 属性pk_jsfs的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_jsfs() {
		 return pk_jsfs;
	  }   
	  
     /**
	   * 属性pk_jsfs的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_jsfs String
	   */
	public void setPk_jsfs(String newPk_jsfs) {
		
		pk_jsfs = newPk_jsfs;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性pk_wldx的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_wldx() {
		 return pk_wldx;
	  }   
	  
     /**
	   * 属性pk_wldx的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_wldx String
	   */
	public void setPk_wldx(String newPk_wldx) {
		
		pk_wldx = newPk_wldx;
	 } 	  
       
        /**
	   * 属性pk_szxm的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_szxm() {
		 return pk_szxm;
	  }   
	  
     /**
	   * 属性pk_szxm的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_szxm String
	   */
	public void setPk_szxm(String newPk_szxm) {
		
		pk_szxm = newPk_szxm;
	 } 	  
       
        /**
	   * 属性ybye的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getYbye() {
		 return ybye;
	  }   
	  
     /**
	   * 属性ybye的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newYbye UFDouble
	   */
	public void setYbye(UFDouble newYbye) {
		
		ybye = newYbye;
	 } 	  
       
        /**
	   * 属性fph的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getFph() {
		 return fph;
	  }   
	  
     /**
	   * 属性fph的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newFph String
	   */
	public void setFph(String newFph) {
		
		fph = newFph;
	 } 	  
       
        /**
	   * 属性dfybje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfybje() {
		 return dfybje;
	  }   
	  
     /**
	   * 属性dfybje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfybje UFDouble
	   */
	public void setDfybje(UFDouble newDfybje) {
		
		dfybje = newDfybje;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性bbhl的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getBbhl() {
		 return bbhl;
	  }   
	  
     /**
	   * 属性bbhl的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newBbhl UFDouble
	   */
	public void setBbhl(UFDouble newBbhl) {
		
		bbhl = newBbhl;
	 } 	  
       
        /**
	   * 属性pk_zx的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_zx() {
		 return pk_zx;
	  }   
	  
     /**
	   * 属性pk_zx的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_zx String
	   */
	public void setPk_zx(String newPk_zx) {
		
		pk_zx = newPk_zx;
	 } 	  
       
        /**
	   * 属性bbye的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getBbye() {
		 return bbye;
	  }   
	  
     /**
	   * 属性bbye的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newBbye UFDouble
	   */
	public void setBbye(UFDouble newBbye) {
		
		bbye = newBbye;
	 } 	  
       
        /**
	   * 属性gyskhh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getGyskhh() {
		 return gyskhh;
	  }   
	  
     /**
	   * 属性gyskhh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newGyskhh String
	   */
	public void setGyskhh(String newGyskhh) {
		
		gyskhh = newGyskhh;
	 } 	  
       
        /**
	   * 属性xh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getXh() {
		 return xh;
	  }   
	  
     /**
	   * 属性xh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newXh String
	   */
	public void setXh(String newXh) {
		
		xh = newXh;
	 } 	  
       
        /**
	   * 属性zy的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getZy() {
		 return zy;
	  }   
	  
     /**
	   * 属性zy的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newZy String
	   */
	public void setZy(String newZy) {
		
		zy = newZy;
	 } 	  
       
        /**
	   * 属性dfbbwsje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfbbwsje() {
		 return dfbbwsje;
	  }   
	  
     /**
	   * 属性dfbbwsje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfbbwsje UFDouble
	   */
	public void setDfbbwsje(UFDouble newDfbbwsje) {
		
		dfbbwsje = newDfbbwsje;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newTs String
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性zyx16的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getZyx16() {
		 return zyx16;
	  }   
	  
     /**
	   * 属性zyx16的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newZyx16 String
	   */
	public void setZyx16(String newZyx16) {
		
		zyx16 = newZyx16;
	 } 	  
       
        /**
	   * 属性dfsl的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfsl() {
		 return dfsl;
	  }   
	  
     /**
	   * 属性dfsl的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfsl UFDouble
	   */
	public void setDfsl(UFDouble newDfsl) {
		
		dfsl = newDfsl;
	 } 	  
       
        /**
	   * 属性hsdj的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getHsdj() {
		 return hsdj;
	  }   
	  
     /**
	   * 属性hsdj的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newHsdj UFDouble
	   */
	public void setHsdj(UFDouble newHsdj) {
		
		hsdj = newHsdj;
	 } 	  
       
        /**
	   * 属性pk_ch的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_ch() {
		 return pk_ch;
	  }   
	  
     /**
	   * 属性pk_ch的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_ch String
	   */
	public void setPk_ch(String newPk_ch) {
		
		pk_ch = newPk_ch;
	 } 	  
       
        /**
	   * 属性pk_fksqd的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_fksqd() {
		 return pk_fksqd;
	  }   
	  
     /**
	   * 属性pk_fksqd的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_fksqd String
	   */
	public void setPk_fksqd(String newPk_fksqd) {
		
		pk_fksqd = newPk_fksqd;
	 } 	  
       
        /**
	   * 属性qxrq的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getQxrq() {
		 return qxrq;
	  }   
	  
     /**
	   * 属性qxrq的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newQxrq String
	   */
	public void setQxrq(String newQxrq) {
		
		qxrq = newQxrq;
	 } 	  
       
        /**
	   * 属性skyhzh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getSkyhzh() {
		 return skyhzh;
	  }   
	  
     /**
	   * 属性skyhzh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newSkyhzh String
	   */
	public void setSkyhzh(String newSkyhzh) {
		
		skyhzh = newSkyhzh;
	 } 	  
       
        /**
	   * 属性pk_xjllxm的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_xjllxm() {
		 return pk_xjllxm;
	  }   
	  
     /**
	   * 属性pk_xjllxm的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_xjllxm String
	   */
	public void setPk_xjllxm(String newPk_xjllxm) {
		
		pk_xjllxm = newPk_xjllxm;
	 } 	  
       
        /**
	   * 属性dfybsj的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfybsj() {
		 return dfybsj;
	  }   
	  
     /**
	   * 属性dfybsj的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfybsj UFDouble
	   */
	public void setDfybsj(UFDouble newDfybsj) {
		
		dfybsj = newDfybsj;
	 } 	  
       
        /**
	   * 属性kslb的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getKslb() {
		 return kslb;
	  }   
	  
     /**
	   * 属性kslb的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newKslb String
	   */
	public void setKslb(String newKslb) {
		
		kslb = newKslb;
	 } 	  
       
        /**
	   * 属性pk_gys的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_gys() {
		 return pk_gys;
	  }   
	  
     /**
	   * 属性pk_gys的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_gys String
	   */
	public void setPk_gys(String newPk_gys) {
		
		pk_gys = newPk_gys;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性pk_ks的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_ks() {
		 return pk_ks;
	  }   
	  
     /**
	   * 属性pk_ks的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_ks String
	   */
	public void setPk_ks(String newPk_ks) {
		
		pk_ks = newPk_ks;
	 } 	  
       
        /**
	   * 属性pk_bz的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_bz() {
		 return pk_bz;
	  }   
	  
     /**
	   * 属性pk_bz的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_bz String
	   */
	public void setPk_bz(String newPk_bz) {
		
		pk_bz = newPk_bz;
	 } 	  
       
        /**
	   * 属性ysje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getYsje() {
		 return ysje;
	  }   
	  
     /**
	   * 属性ysje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newYsje UFDouble
	   */
	public void setYsje(UFDouble newYsje) {
		
		ysje = newYsje;
	 } 	  
       
        /**
	   * 属性dffbje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDffbje() {
		 return dffbje;
	  }   
	  
     /**
	   * 属性dffbje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDffbje UFDouble
	   */
	public void setDffbje(UFDouble newDffbje) {
		
		dffbje = newDffbje;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef10 String
	   */
	public void setVdef10(String newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性pk_xmmc的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_xmmc() {
		 return pk_xmmc;
	  }   
	  
     /**
	   * 属性pk_xmmc的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_xmmc String
	   */
	public void setPk_xmmc(String newPk_xmmc) {
		
		pk_xmmc = newPk_xmmc;
	 } 	  
       
        /**
	   * 属性pk_fksqd_b的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_fksqd_b() {
		 return pk_fksqd_b;
	  }   
	  
     /**
	   * 属性pk_fksqd_b的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_fksqd_b String
	   */
	public void setPk_fksqd_b(String newPk_fksqd_b) {
		
		pk_fksqd_b = newPk_fksqd_b;
	 } 	  
       
        /**
	   * 属性pk_zxxm的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_zxxm() {
		 return pk_zxxm;
	  }   
	  
     /**
	   * 属性pk_zxxm的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_zxxm String
	   */
	public void setPk_zxxm(String newPk_zxxm) {
		
		pk_zxxm = newPk_zxxm;
	 } 	  
       
        /**
	   * 属性fkyhzh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getFkyhzh() {
		 return fkyhzh;
	  }   
	  
     /**
	   * 属性fkyhzh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newFkyhzh String
	   */
	public void setFkyhzh(String newFkyhzh) {
		
		fkyhzh = newFkyhzh;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef7 String
	   */
	public void setVdef7(String newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性pk_km的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_km() {
		 return pk_km;
	  }   
	  
     /**
	   * 属性pk_km的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_km String
	   */
	public void setPk_km(String newPk_km) {
		
		pk_km = newPk_km;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性dffbwsje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDffbwsje() {
		 return dffbwsje;
	  }   
	  
     /**
	   * 属性dffbwsje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDffbwsje UFDouble
	   */
	public void setDffbwsje(UFDouble newDffbwsje) {
		
		dffbwsje = newDffbwsje;
	 } 	  
       
        /**
	   * 属性vmemo的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVmemo() {
		 return vmemo;
	  }   
	  
     /**
	   * 属性vmemo的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVmemo String
	   */
	public void setVmemo(String newVmemo) {
		
		vmemo = newVmemo;
	 } 	  
       
        /**
	   * 属性dfybwsje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfybwsje() {
		 return dfybwsje;
	  }   
	  
     /**
	   * 属性dfybwsje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfybwsje UFDouble
	   */
	public void setDfybwsje(UFDouble newDfybwsje) {
		
		dfybwsje = newDfybwsje;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性dfbbje的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDfbbje() {
		 return dfbbje;
	  }   
	  
     /**
	   * 属性dfbbje的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDfbbje UFDouble
	   */
	public void setDfbbje(UFDouble newDfbbje) {
		
		dfbbje = newDfbbje;
	 } 	  
       
        /**
	   * 属性gg的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getGg() {
		 return gg;
	  }   
	  
     /**
	   * 属性gg的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newGg String
	   */
	public void setGg(String newGg) {
		
		gg = newGg;
	 } 	  
       
        /**
	   * 属性sl的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getSl() {
		 return sl;
	  }   
	  
     /**
	   * 属性sl的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newSl UFDouble
	   */
	public void setSl(UFDouble newSl) {
		
		sl = newSl;
	 } 	  
       
        /**
	   * 属性dffbsj的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getDffbsj() {
		 return dffbsj;
	  }   
	  
     /**
	   * 属性dffbsj的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDffbsj UFDouble
	   */
	public void setDffbsj(UFDouble newDffbsj) {
		
		dffbsj = newDffbsj;
	 } 	  
       
        /**
	   * 属性fbye的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getFbye() {
		 return fbye;
	  }   
	  
     /**
	   * 属性fbye的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newFbye UFDouble
	   */
	public void setFbye(UFDouble newFbye) {
		
		fbye = newFbye;
	 } 	  
       
        /**
	   * 属性pk_ywy的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_ywy() {
		 return pk_ywy;
	  }   
	  
     /**
	   * 属性pk_ywy的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_ywy String
	   */
	public void setPk_ywy(String newPk_ywy) {
		
		pk_ywy = newPk_ywy;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef9 String
	   */
	public void setVdef9(String newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性fbhl的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return UFDouble
	   */
	 public UFDouble getFbhl() {
		 return fbhl;
	  }   
	  
     /**
	   * 属性fbhl的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newFbhl UFDouble
	   */
	public void setFbhl(UFDouble newFbhl) {
		
		fbhl = newFbhl;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef8 String
	   */
	public void setVdef8(String newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性pk_sfkxy的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_sfkxy() {
		 return pk_sfkxy;
	  }   
	  
     /**
	   * 属性pk_sfkxy的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_sfkxy String
	   */
	public void setPk_sfkxy(String newPk_sfkxy) {
		
		pk_sfkxy = newPk_sfkxy;
	 } 	  
       
        /**
	   * 属性pk_bm的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_bm() {
		 return pk_bm;
	  }   
	  
     /**
	   * 属性pk_bm的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_bm String
	   */
	public void setPk_bm(String newPk_bm) {
		
		pk_bm = newPk_bm;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newVdef6 String
	   */
	public void setVdef6(String newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
        /**
	   * 属性ysdbh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getYsdbh() {
		 return ysdbh;
	  }   
	  
     /**
	   * 属性ysdbh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newYsdbh String
	   */
	public void setYsdbh(String newYsdbh) {
		
		ysdbh = newYsdbh;
	 } 	  
       
        /**
	   * 属性pk_zfr的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getPk_zfr() {
		 return pk_zfr;
	  }   
	  
     /**
	   * 属性pk_zfr的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newPk_zfr String
	   */
	public void setPk_zfr(String newPk_zfr) {
		
		pk_zfr = newPk_zfr;
	 } 	  
       
        /**
	   * 属性ddh的Getter方法.
	   *
	   * 创建日期:2014-9-9
	   * @return String
	   */
	 public String getDdh() {
		 return ddh;
	  }   
	  
     /**
	   * 属性ddh的Setter方法.
	   *
	   * 创建日期:2014-9-9
	   * @param newDdh String
	   */
	public void setDdh(String newDdh) {
		
		ddh = newDdh;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-9-9
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-9-9
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_fksqd";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-9-9
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_fksqd_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-9-9
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "arap_fksqd_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-9-9
	  */
	public FksqdBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-9-9
	 * @param newPk_fksqd_b 主键值
	 */
	 public FksqdBVO(String newPk_fksqd_b) {
		
		// 为主键字段赋值:
		 pk_fksqd_b = newPk_fksqd_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-9-9
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_fksqd_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-9-9
	  * @param newPk_fksqd_b  String    
	  */
	 public void setPrimaryKey(String newPk_fksqd_b) {
				
				pk_fksqd_b = newPk_fksqd_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-9-9
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "arap_fksqd_b"; 
				
	 } 
} 
