/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product.                              *
\***************************************************************/

package nc.vo.ct.pub;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import nc.vo.dm.pub.DMDataVO;

/**
 * 合同单据表体VO。
 * 创建日期：(2001-8-23)
 * @author：lengjg
 */
public class ManageItemVO extends DMDataVO {

	/**
	 * 使用主键字段进行初始化的构造子。
	 *
	 * 创建日期：(2001-8-23)
	 */
	public ManageItemVO() {
		super();
	}
	/**
	 * 使用主键进行初始化的构造子。
	 *
	 * 创建日期：(2001-8-23)
	 * @param ??fieldNameForMethod?? 主键值
	 */
	public ManageItemVO(String newPk_ct_manage_b) {
		super();
		// 为主键字段赋值:
		setAttributeValue("pk_ct_manage_b", newPk_ct_manage_b);
	}

	/**
	 * 返回对象标识，用来唯一定位对象。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getPrimaryKey() {

		return (String) getAttributeValue("pk_ct_manage_b");
	}
	/**
	 * 设置对象标识，用来唯一定位对象。
	 *
	 * 创建日期：(2001-8-23)
	 * @param pk_ct_manage_b String 
	 */
	public void setPrimaryKey(String newPk_ct_manage_b) {

		setAttributeValue("pk_ct_manage_b", newPk_ct_manage_b);
	}
	/**
	 * 属性pk_ct_manage_b的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getPk_ct_manage_b() {
		return (String) getAttributeValue("pk_ct_manage_b");
	}
	/**
	 * 属性pk_ct_manage的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getPk_ct_manage() {
		return  (String)getAttributeValue("pk_ct_manage");
	}
	/**
	 * 属性pk_corp的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getPk_corp() {
		return (String) getAttributeValue("pk_corp");
	}
	/**
	 * 属性invid的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getInvid() {
		return (String) getAttributeValue("invid");
	}
/**
 * 属性delivdate的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDate
 */
public UFDate getDelivdate() {
	return getAttributeValue("delivdate") == null
		? null
		: new UFDate(getAttributeValue("delivdate").toString());
}
/**
 * 属性amount的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getAmount() {
	return getAttributeValue("amount") == null
		? null
		: new UFDouble(getAttributeValue("amount").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOriprice() {
	return getAttributeValue("oriprice") == null
		? null
		: new UFDouble(getAttributeValue("oriprice").toString());
}
/**
 * 属性natiprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getNatiprice() {
	return getAttributeValue("natiprice") == null
		? null
		: new UFDouble(getAttributeValue("natiprice").toString());
}
/**
 * 属性natisum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getNatisum() {
	return getAttributeValue("natisum") == null
		? null
		: new UFDouble(getAttributeValue("natisum").toString());
}
/**
 * 属性orisum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOrisum() {
	return getAttributeValue("orisum") == null
		? null
		: new UFDouble(getAttributeValue("orisum").toString());
}
/**
 * 属性taxration的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getTaxration() {
	return getAttributeValue("taxration") == null
		? null
		: new UFDouble(getAttributeValue("taxration").toString());
}
/**
 * 属性ordprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOrdprice() {
	return getAttributeValue("ordprice") == null
		? null
		: new UFDouble(getAttributeValue("ordprice").toString());
}
/**
 * 属性ordnum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOrdnum() {
	return getAttributeValue("ordnum") == null
		? null
		: new UFDouble(getAttributeValue("ordnum").toString());
}
/**
 * 属性ordsum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOrdsum() {
	return getAttributeValue("ordsum") == null
		? null
		: new UFDouble(getAttributeValue("ordsum").toString());
}
/**
 * 属性inoutnum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getInoutnum() {
	return getAttributeValue("inoutnum") == null
		? null
		: new UFDouble(getAttributeValue("inoutnum").toString());
}
/**
 * 属性inoutsum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getInoutsum() {
	return getAttributeValue("inoutsum") == null
		? null
		: new UFDouble(getAttributeValue("inoutsum").toString());
}
/**
 * 属性invoicnum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getInvoicnum() {
	return getAttributeValue("invoicnum") == null
		? null
		: new UFDouble(getAttributeValue("invoicnum").toString());
}
/**
 * 属性invoicesum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getInvoicesum() {
	return getAttributeValue("invoicesum") == null
		? null
		: new UFDouble(getAttributeValue("invoicesum").toString());
}
/**
 * 属性paysum的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getPaysum() {
	return getAttributeValue("paysum") == null
		? null
		: new UFDouble(getAttributeValue("paysum").toString());
}
/**
 * 属性earlydate的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDate
 */
public UFDate getEarlydate() {
	return getAttributeValue("earlydate") == null
		? null
		: new UFDate(getAttributeValue("earlydate").toString());
}
	/**
	 * 属性pk_ct_manage_b的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newpk_ct_manage_b String
	 */
	public void setPk_ct_manage_b(String newPk_ct_manage_b) {

		setAttributeValue("pk_ct_manage_b", newPk_ct_manage_b);
	}
	/**
	 * 属性pk_ct_manage的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newpk_ct_manage String
	 */
	public void setPk_ct_manage(String newPk_ct_manage) {

		setAttributeValue("pk_ct_manage", newPk_ct_manage);
	}
	/**
	 * 属性pk_corp的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newpk_corp String
	 */
	public void setPk_corp(String newPk_corp) {

		setAttributeValue("pk_corp", newPk_corp);
	}
	/**
	 * 属性invid的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newinvid String
	 */
	public void setInvid(String newInvid) {

		setAttributeValue("invid", newInvid);
	}
	/**
	 * 属性delivdate的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdelivdate UFDate
	 */
	public void setDelivdate(UFDate newDelivdate) {

		setAttributeValue("delivdate", newDelivdate);
	}
	/**
	 * 属性amount的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newamount UFDouble
	 */
	public void setAmount(UFDouble newAmount) {

		setAttributeValue("amount", newAmount);
	}
	
	public void setDpzk(UFDouble newAmount) {

		setAttributeValue("dpzk", newAmount);
	}
	
	public UFDouble getDpzk() {
		return getAttributeValue("dpzk") == null
			? null
			: new UFDouble(getAttributeValue("dpzk").toString());
	}
	
	public void setTsbl(UFDouble newAmount) {

		setAttributeValue("tsbl", newAmount);
	}
	
	public UFDouble getTsbl() {
		return getAttributeValue("tsbl") == null
			? null
			: new UFDouble(getAttributeValue("tsbl").toString());
	}
	
	/**
	 * 属性def1的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef1 String
	 */
	public void setDef1(String newDef1) {

		setAttributeValue("def1", newDef1);
	}
	/**
	 * 属性def2的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef2 String
	 */
	public void setDef2(String newDef2) {

		setAttributeValue("def2", newDef2);
	}
	/**
	 * 属性def3的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef3 String
	 */
	public void setDef3(String newDef3) {

		setAttributeValue("def3", newDef3);
	}
	/**
	 * 属性def4的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef4 String
	 */
	public void setDef4(String newDef4) {

		setAttributeValue("def4", newDef4);
	}
	/**
	 * 属性def5的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef5 String
	 */
	public void setDef5(String newDef5) {

		setAttributeValue("def5", newDef5);
	}
	/**
	 * 属性def6的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef6 String
	 */
	public void setDef6(String newDef6) {

		setAttributeValue("def6", newDef6);
	}
	/**
	 * 属性def7的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef7 String
	 */
	public void setDef7(String newDef7) {

		setAttributeValue("def7", newDef7);
	}
	/**
	 * 属性def8的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef8 String
	 */
	public void setDef8(String newDef8) {

		setAttributeValue("def8", newDef8);
	}
	/**
	 * 属性def9的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef9 String
	 */
	public void setDef9(String newDef9) {

		setAttributeValue("def9", newDef9);
	}
	/**
	 * 属性def10的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef10 String
	 */
	public void setDef10(String newDef10) {

		setAttributeValue("def10", newDef10);
	}

	/**
	 * 属性oriprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param neworiprice UFDouble
	 */
	public void setOriprice(UFDouble newOriprice) {

		setAttributeValue("oriprice", newOriprice);
	}
	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setNatiprice(UFDouble newNatiprice) {

		setAttributeValue("natiprice", newNatiprice);
	}
	/**
	 * 属性natisum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatisum UFDouble
	 */
	public void setNatisum(UFDouble newNatisum) {

		setAttributeValue("natisum", newNatisum);
	}
	/**
	 * 属性orisum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param neworisum UFDouble
	 */
	public void setOrisum(UFDouble newOrisum) {

		setAttributeValue("orisum", newOrisum);
	}
	/**
	 * 属性taxration的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newtaxration UFDouble
	 */
	public void setTaxration(UFDouble newTaxration) {

		setAttributeValue("taxration", newTaxration);
	}
	/**
	 * 属性ordprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newordprice UFDouble
	 */
	public void setOrdprice(UFDouble newOrdprice) {

		setAttributeValue("ordprice", newOrdprice);
	}
	/**
	 * 属性ordnum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newordnum UFDouble
	 */
	public void setOrdnum(UFDouble newOrdnum) {

		setAttributeValue("ordnum", newOrdnum);
	}
	/**
	 * 属性ordsum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newordsum UFDouble
	 */
	public void setOrdsum(UFDouble newOrdsum) {

		setAttributeValue("ordsum", newOrdsum);
	}
	/**
	 * 属性inoutnum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newinoutnum UFDouble
	 */
	public void setInoutnum(UFDouble newInoutnum) {

		setAttributeValue("inoutnum", newInoutnum);
	}
	/**
	 * 属性inoutsum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newinoutsum UFDouble
	 */
	public void setInoutsum(UFDouble newInoutsum) {

		setAttributeValue("inoutsum", newInoutsum);
	}
	/**
	 * 属性invoicnum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newinvoicnum UFDouble
	 */
	public void setInvoicnum(UFDouble newInvoicnum) {

		setAttributeValue("invoicnum", newInvoicnum);
	}
	/**
	 * 属性invoicesum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newinvoicesum UFDouble
	 */
	public void setInvoicesum(UFDouble newInvoicesum) {

		setAttributeValue("invoicesum", newInvoicesum);
	}
	/**
	 * 属性paysum的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newpaysum UFDouble
	 */
	public void setPaysum(UFDouble newPaysum) {

		setAttributeValue("paysum", newPaysum);
	}
	/**
	 * 属性earlydate的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newearlydate UFDate
	 */
	public void setEarlydate(UFDate newEarlydate) {

		setAttributeValue("earlydate", newEarlydate);
	}
	/**
	 * 验证对象各属性之间的数据逻辑正确性。
	 *
	 * 创建日期：(2001-8-23)
	 * @exception nc.vo.pub.ValidationException 如果验证失败，抛出
	 *     ValidationException，对错误进行解释。
	 */
	public void validate() throws ValidationException {

		ArrayList errFields= new ArrayList();
		// errFields record those null fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值，你可能需要修改下面的提示信息：

//		if (getInvid()!=null) {
//			boolean bIsManagedByAstmeas= nc.ui.scm.pub.invmeas.InvMeasInfo.isManagedByAstmeas(getInvid());
//			if(bIsManagedByAstmeas){
//				if(getAttributeValue("astmeasid") == null)
//				    errFields.add(new String(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("common","UC000-0003938")/*@res "辅单位"*/));
//				if(getAttributeValue("astnum") == null)
//				    errFields.add(new String(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("common","UC000-0003971")/*@res "辅数量"*/));
//			}
//		}
		//if (amount ",", null) {
		//	errFields.add(new String("存货数量"));
		//}
		//if (measid ",", null) {
		//	errFields.add(new String("计量单位"));
		//}
		//if ( getAttributeValue("taxration") == null) {
			//errFields.add(new String("税率"));
		//}
		//if ( getAttributeValue("delivdate") == null) {
			//errFields.add(new String("计划收发货日期"));
		//}
		//if (oriprice == null) {
		//	errFields.add(new String("原币单价"));
		//}
		//if (orisum == null) {
		//	errFields.add(new String("原币金额"));
		//}
		//if (natiprice == null) {
		//	errFields.add(new String("本币单价"));
		//}
		//if (natisum == null) {
		//	errFields.add(new String("本币金额"));
		//}

		// construct the exception message:
		StringBuffer message= new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("4020pub","UPP4020pub-000168")/*@res "下列字段不能为空："*/);
		if (errFields.size() > 0) {
			String[] temp= (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i= 1; i < temp.length; i++) {
				message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("SCMCOMMON","UPPSCMCommon-000000")/*@res "、"*/);
				message.append(temp[i]);
			}
			// throw the exception:
			throw new NullFieldException(message.toString());
		}
	}

/**
 * 
 * 功能：
 * 参数： 
 * 返回：
 * 例外：
 * 日期：(2002-8-28 15:53:25)
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 注释标志：
 * @return java.lang.Integer
 */
public Integer getDr() {
	return getAttributeValue("dr") == null
		? null
		: new Integer(getAttributeValue("dr").toString());
}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:40:28)
	 * @return java.lang.String
	 */
	public String getInvclasscode() {
		return (String) getAttributeValue("invclasscode");
	}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:41:05)
	 * @return java.lang.String
	 */
	public String getInvclassname() {
		return (String) getAttributeValue("invclassname");
	}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:39:10)
	 */
	public String getInvclid() {
		return (String) getAttributeValue("invclid");
	}

	/**
	 * 属性pk_corp的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return String
	 */
	public String getInvname() {
		return(String)  getAttributeValue("invname");
	}

	/**
	 * 属性piece的Getter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @return UFDouble
	 */
	public String getMeasid() {
		return (String) getAttributeValue("measid");
	}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getNatitax() {
	return getAttributeValue("natitaxmny") == null
		? null
		: new UFDouble(getAttributeValue("natitaxmny").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getNatitaxprice() {
	return getAttributeValue("natitaxprice") == null
		? null
		: new UFDouble(getAttributeValue("natitaxprice").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getNatitaxsum() {
	return getAttributeValue("natitaxsummny") == null
		? null
		: new UFDouble(getAttributeValue("natitaxsummny").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNbitmny() {
	return getAttributeValue("nbitmny") == null
		? null
		: new UFDouble(getAttributeValue("nbitmny").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNbitprice() {
	return getAttributeValue("nbitprice") == null
		? null
		: new UFDouble(getAttributeValue("nbitprice").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNmny1() {
	return getAttributeValue("nmny1") == null
		? null
		: new UFDouble(getAttributeValue("nmny1").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNmny2() {
	return getAttributeValue("nmny2") == null
		? null
		: new UFDouble(getAttributeValue("nmny2").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNprice1() {
	return getAttributeValue("nprice1") == null
		? null
		: new UFDouble(getAttributeValue("nprice1").toString());
}

/**
 * 类型说明：
 * 创建日期：(2002-10-24 15:36:08)
 * 作者：赵宇煌
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 算法说明：
 * @return nc.vo.pub.lang.UFDouble
 */
public nc.vo.pub.lang.UFDouble getNprice2() {
	return getAttributeValue("nprice2") == null
		? null
		: new UFDouble(getAttributeValue("nprice2").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOritax() {
	return getAttributeValue("oritaxmny") == null
		? null
		: new UFDouble(getAttributeValue("oritaxmny").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOritaxprice() {
	return getAttributeValue("oritaxprice") == null
		? null
		: new UFDouble(getAttributeValue("oritaxprice").toString());
}

/**
 * 属性oriprice的Getter方法。
 *
 * 创建日期：(2001-8-23)
 * @return UFDouble
 */
public UFDouble getOritaxsum() {
	return getAttributeValue("oritaxsummny") == null
		? null
		: new UFDouble(getAttributeValue("oritaxsummny").toString());
}



	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @return java.lang.String
	 */
	public java.lang.String getVcontext() {
		return(String)  getAttributeValue("vcontext");
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 13:53:24)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @return java.lang.String
	 */
	public java.lang.String getVinvspec() {
		return (String) getAttributeValue("invspec");
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 13:53:24)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @return java.lang.String
	 */
	public java.lang.String getVinvtype() {
		return  (String)getAttributeValue("invtype");
	}

	/**
	 * 
	 * 功能：
	 * 参数： 
	 * 返回：
	 * 例外：
	 * 日期：(2002-8-28 16:03:23)
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 注释标志：
	 * @param dr java.lang.Integer
	 */
	public void setDr(Integer dr) {
		setAttributeValue("dr", dr);
	}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:43:49)
	 * @param newInvclasscode java.lang.String
	 */
	public void setInvclasscode(String newInvclasscode) {
		setAttributeValue("invclasscode", newInvclasscode);
	}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:45:15)
	 * @param newInvclassname java.lang.String
	 */
	public void setInvclassname(String newInvclassname) {
		setAttributeValue("invclassname", newInvclassname);
	}

	/**
	 * 此处插入方法说明。
	 * 创建日期：(2002-4-28 11:42:10)
	 * @param newInvclid java.lang.String
	 */
	public void setInvclid(String newInvclid) {
		setAttributeValue("invclid", newInvclid);
	}

	/**
	 * 属性def9的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newdef9 String
	 */
	public void setInvname(String newInvName) {

		setAttributeValue("invname", newInvName);
	}

	/**
	 * 属性piece的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newpiece UFDouble
	 */
	public void setMeasid(String newMeasid) {

		setAttributeValue("measid", newMeasid);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setNatitax(UFDouble newNatitax) {

		setAttributeValue("natitaxmny", newNatitax);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setNatitaxprice(UFDouble newNatitaxprice) {

		setAttributeValue("natitaxprice", newNatitaxprice);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setNatitaxsum(UFDouble newNatitaxsum) {

		setAttributeValue("natitaxsummny", newNatitaxsum);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnbitmny nc.vo.pub.lang.UFDouble
	 */
	public void setNbitmny(nc.vo.pub.lang.UFDouble newnbitmny) {
		setAttributeValue("nbitmny", newnbitmny);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnbitprice nc.vo.pub.lang.UFDouble
	 */
	public void setNbitprice(nc.vo.pub.lang.UFDouble newnbitprice) {
		setAttributeValue("nbitprice", newnbitprice);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnmny1 nc.vo.pub.lang.UFDouble
	 */
	public void setNmny1(nc.vo.pub.lang.UFDouble newnmny1) {
		setAttributeValue("nmny1", newnmny1);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnmny2 nc.vo.pub.lang.UFDouble
	 */
	public void setNmny2(nc.vo.pub.lang.UFDouble newnmny2) {
		setAttributeValue("nmny2", newnmny2);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnprice1 nc.vo.pub.lang.UFDouble
	 */
	public void setNprice1(nc.vo.pub.lang.UFDouble newnprice1) {
		setAttributeValue("nprice1", newnprice1);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newnprice2 nc.vo.pub.lang.UFDouble
	 */
	public void setNprice2(nc.vo.pub.lang.UFDouble newnprice2) {
		setAttributeValue("nprice2", newnprice2);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setOritax(UFDouble newOritax) {

		setAttributeValue("oritaxmny", newOritax);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setOritaxprice(UFDouble newOritaxprice) {

		setAttributeValue("oritaxprice", newOritaxprice);
	}

	/**
	 * 属性natiprice的setter方法。
	 *
	 * 创建日期：(2001-8-23)
	 * @param newnatiprice UFDouble
	 */
	public void setOritaxsum(UFDouble newOritaxsum) {

		setAttributeValue("oritaxsummny", newOritaxsum);
	}



	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 15:36:08)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newvcontext java.lang.String
	 */
	public void setVcontext(java.lang.String newvcontext) {
		setAttributeValue("vcontext", newvcontext);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 13:53:24)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newinvspec java.lang.String
	 */
	public void setVinvspec(java.lang.String newinvspec) {
		setAttributeValue("invspec", newinvspec);
	}

	/**
	 * 类型说明：
	 * 创建日期：(2002-10-24 13:53:24)
	 * 作者：赵宇煌
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 算法说明：
	 * @param newinvtype java.lang.String
	 */
	public void setVinvtype(java.lang.String newinvtype) {
		setAttributeValue("invtype", newinvtype);
	}

/**
 * 
 * 功能：
 * 参数： 
 * 返回：
 * 例外：
 * 日期：(2002-9-10 14:39:43)
 * 修改日期：
 * 修改人：
 * 修改原因：
 * 注释标志：
 * @return nc.vo.pub.lang.UFDateTime
 */
public String getTs() {
	return (String)getAttributeValue("ts");
		
}

/**
 * 属性spec的setter方法。
 *
 * 创建日期：(2001-8-23)
 * @param newspec String
 */
public void setSpec(String newSpec) {

	//spec = newSpec;
}

	/**
	 * 
	 * 功能：
	 * 参数： 
	 * 返回：
	 * 例外：
	 * 日期：(2002-9-10 14:36:19)
	 * 修改日期：
	 * 修改人：
	 * 修改原因：
	 * 注释标志：
	 * @param ts nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(String ts) {
		setAttributeValue("ts", ts);
	}
}